
baselineDecM = c("raterDecAvgM", "decAvgW","avgWaveDecM")
baselineDecW = c("raterDecAvgW", "decAvgM","avgWaveDecW")

menFeatures = c(baselineDecM, 
             "datesCrossProbDecM", 
             "datesManProbDecM",
             "fieldsCrossProbDecM", 
             "goalsCrossProbDecM",
             "decAvgM",
             "exphappyM",
             "attrAvgRatingW",
             "likeAvgRatingW",
             "careerAcademicM_careerAcademicWCross",
             "raterDecAvgW",
             "impreligW",
             "careersManProbDecM",
             "sincAvgRatingW",
             "yogaPhysActM",
             "shoppingWealthIndW",
             "incomeWealthIndW",
             "goalsManProbDecM",
             "yogaPhysActW",
             "funPrefW",
             "diningWealthIndW",
             "avgWaveDecW",
             "goalFunNightM_goalFunNightWCross",
             "raceWhiteW",
             "tvsportsMiscActW",
             "metM",
             "hikingPhysActW",
             "fieldScienceM",
             "ageW",
             "exphappyW",
             "sincPrefW",
             "sharPrefM",
             "raceAsianM",
             "goOutW",
             "fieldBusinessW",
             "impraceM",
             "goalMeetNewW",
             "goalFunNightM_goalMeetNewWCross",
             "likeAvgRatingM",
             "hikingPhysActM",
             "theaterArtActW",
             "theaterArtActM",
             "careerFinanceM_careerAcademicWCross",
             "raceAsianM_raceWhiteWCross",
             "probAvgRatingM",
             "concertsMiscActM",
             "artArtActM",
             "date7M",
             "goalMeetNewM",
             "fieldsWomanProbDecM",
             "racesWomanProbDecM",
             "impreligM",
             "incomeWealthIndM",
             "dateM",
             "goOutM",
             "sportsPhysActM",
             "clubbingMiscActM",
             "readingArtActM",
             "shoppingWealthIndM",
             "museumsArtActW",
             "gamingMiscActW",
             "moviesArtActW",
             "musicArtActW",
             "raceAsianW",
             "goalMeetNewM_goalMeetNewWCross")



womenFeatures = c(baselineDecW, 
             "attrAvgRatingM", 
             "datesCrossProbDecW", 
             "fieldsCrossProbDecW", 
             "goalsCrossProbDecW",
             "careersWomanProbDecW", 
             "careersCrossProbDecW", 
             "exphappyW", 
             "raterDecAvgM", 
             "funAvgRatingM",
             "avgWaveDecM", 
             "probAvgRatingM", 
             "ageM", 
             "raceWhiteM_raceWhiteWCross", 
             "raceWhiteW",
             "museumsArtActW", 
             "intelAvgRatingW", 
             "shoppingWealthIndW",
             "intelAvgRatingM",
             "goOutM",
             "ambPrefM",
             "tvsportsMiscActW",
             "date3W",
             "raceAsianW",
             "incomeWealthIndM",
             "diningWealthIndM",
             "decAvgW",
             "impraceW",
             "raceWhiteM_raceAsianWCross",
             "incomeWealthIndW",
             "raceWhiteM",
             "gamingMiscActM",
             "sharPrefW",
             "careerAcademicW",
             "careerFinanceW",
             "moviesArtActW",
             "hikingPhysActM",
             "exercisePhysActW",
             "goalsWomanProbDecW",
             "fieldsManProbDecW",
             "tvMiscActW",
             "date7W",
             "fieldsWomanProbDecW",
             "readingArtActW")


matchFeatures = c("attrAvgRatingM", "decAvgM", "goalsCrossProbMatch", "funAvgRatingM",
             "fieldsCrossProbMatch", "careerAcademicM_careerAcademicWCross", "matchAvgM", "datesCrossProbMatch",
             "ageM", "concertsMiscActW", "incomeWealthIndM", "matchAvgW", "date6M", "shoppingWealthIndW",
             "exercisePhysActM", "readingArtActM", "yogaPhysActM", "impraceW", "fieldsCrossProbDecM", "racesWomanProbDecW",
             "careerFinanceW", "raceAsianM_raceWhiteWCross", "avgWaveDecM", "attrAvgRatingW", "artArtActW",
             "incomeWealthIndW", "avgWaveDecW", "raterDecAvgW", "careersWomanProbDecW",
             "raceWhiteW", "impreligW", "moviesArtActW", "diningWealthIndW", "exphappyM", "fieldsWomanProbDecW",
             "careersCrossProbMatch", "probAvgRatingM", "racesManProbDecM", "careerFinanceM", "sincAvgRatingW",
             "date3W", "intelPrefW", "intelAvgRatingW", "attrPrefM", "intelPrefM","fieldScienceM",
             "musicArtActW", "careersWomanProbDecM", "gamingMiscActW", "raceAsianW", "hikingPhysActW", "date4M_date6WCross",
             "racesWomanProbDecM", "tvMiscActW", "theaterArtActW", "fieldScienceW", "matchAvgW", "raceWhiteM_raceAsianWCross", 
             "goalMeetNewM_goalMeetNewWCross", "fieldBusinessW", "datesWomanProbDecW","raterDecAvgM", "goalsWomanProbDecM",
             "fieldBusinessW", "sharPrefW")

write.csv(merged, '~/Desktop/speedDating/matchGuessesAdded.csv')
